INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('1', 'Fruits', 'category_images/Fruits_jJ3Eka0.jpeg', 'fruits');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('2', 'Vegetables', 'category_images/Vegetables_aK8SL0G.jpeg', 'vegetables');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('3', 'Dairy', 'category_images/Dairy.jpeg', 'dairy');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('4', 'Meat', 'category_images/Meat.jpeg', 'meat');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('5', 'Beverages', 'category_images/Beverages-1.jpeg', 'beverages');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('6', 'Pastries', 'category_images/Confectionaries.jpeg', 'pastries');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('7', 'Stationary', 'category_images/Stationary.jpeg', 'stationary');
INSERT INTO "main"."basket_app_category" ("id", "cname", "cpic", "slug") VALUES ('8', 'Household', 'category_images/household.jpeg', 'household');

INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('1', 'Cheese', '50', 'product_images/Cheese.jpeg', '3', '200 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('2', 'Curd', '50', 'product_images/Curd.jpeg', '3', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('3', 'Butter', '50', 'product_images/Butter.jpeg', '3', '100 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('4', 'Paneer', '20', 'product_images/Paneer_avf8v8b.jpeg', '3', '250 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('5', 'Milk', '100', 'product_images/Milk.jpeg', '3', '500 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('6', 'Chicken Breast', '120', 'product_images/Chicken_Breast_8ZTiwEk.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('7', 'Chicken Drumstick', '150', 'product_images/Chicken_Drumstick_phXUJ1p.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('8', 'Chicken Wings', '100', 'product_images/Chicken_Wings_L3LxJfI.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('9', 'Lamb Loins', '450', 'product_images/Lamb_Loins.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('10', 'Lamb Chops', '480', 'product_images/Lamb_Chops_wjwalEc.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('11', 'Beef Ribs', '600', 'product_images/Beef_Ribs_Xt9B0sG.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('12', 'Pork Belly', '400', 'product_images/Pork_Belly_puPsM7K.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('13', 'Pork Butt', '250', 'product_images/Pork_Butt.jpeg', '4', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('14', 'Onion', '40', 'product_images/Onion.jpeg', '2', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('15', 'Tomato', '20', 'product_images/Tomato.jpeg', '2', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('16', 'Potato', '30', 'product_images/Potato.jpeg', '2', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('17', 'Beans', '120', 'product_images/Beans.jpeg', '2', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('18', 'Corn', '30', 'product_images/Corn.jpeg', '2', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('19', 'Cauliflower', '25', 'product_images/Cauliflower.jpeg', '2', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('20', 'Chilli', '16', 'product_images/Chilli.jpeg', '2', '250 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('21', 'Cucumber', '37', 'product_images/Cucumber.jpeg', '2', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('22', 'Capsicum', '35', 'product_images/Capsicum.jpeg', '2', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('23', 'Eggplant', '10', 'product_images/Eggplant.jpeg', '2', '250 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('24', 'Carrot', '33', 'product_images/Carrot.jpeg', '2', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('25', 'Bitter Gourd', '26', 'product_images/Bitter_Gourd.jpeg', '2', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('26', 'Apple', '250', 'product_images/Apple.jpeg', '1', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('27', 'Banana', '56', 'product_images/Banana.jpeg', '1', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('28', 'Mango', '56', 'product_images/Mango.jpeg', '1', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('29', 'Orange', '24', 'product_images/Orange.jpeg', '1', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('30', 'Watermelon', '84', 'product_images/Watermelon.jpeg', '1', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('31', 'Green Grapes', '88', 'product_images/Green_Grapes.jpeg', '1', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('32', 'Pineapple', '38', 'product_images/Pineapple.jpeg', '1', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('33', 'Pomogranate', '148', 'product_images/Pomogranate.jpeg', '1', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('34', 'Guava', '35', 'product_images/Guava_6h1Y7f5.jpeg', '1', '500 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('35', 'Coconut', '40', 'product_images/Coconut.jpeg', '1', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('36', 'Papaya', '78', 'product_images/Papaya.jpeg', '1', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('37', 'Avacado', '150', 'product_images/Avacado.jpeg', '1', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('38', 'Fresh Cream', '60', 'product_images/Sour_Cream.jpeg', '3', '250 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('39', 'Condensed Milk', '115', 'product_images/Condensed_Milk.jpeg', '3', '400 g');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('40', 'Milkshake', '14', 'product_images/Milkshake.jpeg', '3', '200 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('41', 'Pepsi', '22', 'product_images/Pepsi.jpeg', '5', 'can');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('42', 'Mountain Dew', '40', 'product_images/Mtndew_LJBh3xh.jpeg', '5', '750 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('43', 'Sprite', '25', 'product_images/Sprite_2.jpeg', '5', '250 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('44', 'Coca Cola', '40', 'product_images/Coca_Cola.jpeg', '5', 'can');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('45', 'Tropicana Asssorted', '92', 'product_images/Tropicana.jpeg', '5', 'L');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('46', 'Heineken', '270', 'product_images/Heineken_5UL3msP.jpeg', '5', '250 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('47', 'Juice Assorted', '53', 'product_images/Juice.jpeg', '5', '500 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('48', 'Ginger Ale', '100', 'product_images/Ginger_Ale.jpeg', '5', '250 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('49', 'Bread', '35', 'product_images/Bread.jpeg', '6', 'loaf');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('50', 'Chocolate Cupcake', '120', 'product_images/Cupcake.jpeg', '6', 'packet(6 pcs)');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('51', 'Chicken Puffs', '25', 'product_images/Puffs.jpeg', '6', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('52', 'Cream Bun', '30', 'product_images/Cream_Bun.jpeg', '6', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('53', 'Donut Assorted', '40', 'product_images/Donut.jpeg', '6', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('54', 'Tea Cake', '20', 'product_images/Tea_Cake.jpeg', '6', 'packet');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('55', 'Chicken Sandwich', '30', 'product_images/Sandwich.jpeg', '6', 'slice');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('56', 'Chicken Burger', '60', 'product_images/Burger_Y2OkYmD.jpeg', '6', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('57', 'Pencil (pack of 10)', '50', 'product_images/Pencil.jpeg', '7', 'pack');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('58', 'Eraser (pack of 3)', '18', 'product_images/Eraser.jpeg', '7', 'pack');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('59', 'Ruled Notebook', '30', 'product_images/Ruled_book.jpeg', '7', 'book(100 pgs)');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('60', 'Ruler (30cm)', '25', 'product_images/Ruler.jpeg', '7', 'ruler');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('61', 'Geometry Box', '150', 'product_images/geometry_box.jpeg', '7', 'box');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('62', 'Stapler', '63', 'product_images/Stapler.jpeg', '7', 'pc');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('63', 'Highlighter', '120', 'product_images/Highlighter.jpeg', '7', 'pack of 6');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('64', 'Ball Pen', '60', 'product_images/Pen.jpeg', '7', 'pen');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('65', 'Harpic', '170', 'product_images/harpic.jpeg', '8', '500 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('66', 'Dettol', '100', 'product_images/dettol.jpeg', '8', '500 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('67', 'Surf Excel', '350', 'product_images/surfexcel.jpeg', '8', 'kg');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('68', 'Odonil', '70', 'product_images/odonil.jpeg', '8', 'packet');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('69', 'Comfort', '200', 'product_images/comfort.jpeg', '8', 'L');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('70', 'Air Freshener', '150', 'product_images/Air_freshener.jpeg', '8', 'bottle');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('71', 'Lifebuoy', '200', 'product_images/Lifebuoy.jpeg', '8', '100 mL');
INSERT INTO "main"."basket_app_product" ("id", "pname", "price", "ppic", "category_id", "amount") VALUES ('72', 'Lizol Floor Cleaner', '150', 'product_images/floorcleaner.jpeg', '8', '400 mL');