# Generated by Django 3.2.3 on 2021-06-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0004_auto_20210612_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cpic',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
