# Generated by Django 3.2.3 on 2021-06-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0005_alter_category_cpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
