# Generated by Django 3.2.3 on 2021-06-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
    ]
