# Generated by Django 3.2.3 on 2021-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.CharField(default='1kg', max_length=20),
            preserve_default=False,
        ),
    ]
