# Generated by Django 3.2.3 on 2021-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0008_product_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_item',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
