# Generated by Django 3.2.3 on 2021-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0013_alter_customer_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneno',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
