# Generated by Django 3.2.3 on 2021-06-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0014_alter_customer_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phoneno',
            new_name='phone',
        ),
    ]
