# Generated by Django 3.2.3 on 2021-06-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0015_rename_phoneno_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneno',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
