# Generated by Django 3.2.3 on 2021-06-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0016_auto_20210614_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
