# Generated by Django 3.2.3 on 2021-06-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0018_remove_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
