# Generated by Django 3.2.3 on 2021-06-14 07:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0020_auto_20210614_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
    ]
