# Generated by Django 3.2.3 on 2021-06-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0027_auto_20210614_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
