# Generated by Django 3.2.3 on 2021-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_app', '0030_alter_receiver_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
